learning_templates/basicapp/urls.py
from django.conf.urls import url
from basicapp import views

app_name = 'basicapp'

urlpatterns = [
    url(r'^other/$',views.other,name='other'),
    url(r'^relative/$',views.relative,name='relative'),

]

learning_templates/learning_templates/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import url,include
from basicapp import views

urlpatterns = [
    path('admin/', admin.site.urls),
    url(r'^$',views.index,name='index'),
    url(r'^basicapp/',include('basicapp.urls')),
]

learning_templates/basicapp/models.py
from django.db import models

# Create your models here.

learning_templates/basicapp/views.py
from django.shortcuts import render

# Create your views here.
def index(request):
    context = {'text':'hello world'}
    return render(request,'basicapp/index.html',context)

def other(request):
    return render(request,'basicapp/other.html')

def relative(request):
    return render(request,'basicapp/relative_url_template.html')

learning_templates/templates/basicapp/index.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title></title>
  </head>
  <body>
    <h1>Welcome to index</h1>
    {{ text|cut:'hello' }}
  </body>
</html>

learning_templates/templates/basicapp/other.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title></title>
  </head>
  <body>
    <h1>welcome to other</h1>
  </body>
</html>

learning_templates/templates/basicapp/relative_url_template.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title></title>
  </head>
  <body>
    <h1>welcome to relative url templates</h1>
    <a href= "{% url 'basicapp:other' %}" >the other page</a>
    <a href="{% url 'admin:index' %}">link to admin</a>
    <a href="{% url 'index' %}">link to index</a>
  </body>
</html>